DESCRIBE baran;
select*from baran;
DROP TABLE TV_SERIES;
CREATE TABLE TV_SERIES
(
IND INT  PRIMARY KEY AUTO_INCREMENT ,
SERIES_NAME VARCHAR(30),
SERIES_RATINGS DECIMAL(3,2),
SERIES_IMDB DECIMAL (2,1),
SERIES_HERO VARCHAR(30)
);
ALTER TABLE TV_SERIES 
MODIFY SERIES_RATINGS DECIMAL(2,1);
INSERT INTO  TV_SERIES(SERIES_NAME,SERIES_RATINGS,SERIES_IMDB,SERIES_HERO)
VALUES("BREAKING BAD",4.8,9.5,"WALTER WHITE");
SELECT*FROM TV_SERIES
WHERE SERIES_RATINGS IS NOT NULL;


INSERT INTO  TV_SERIES(SERIES_NAME,SERIES_RATINGS,SERIES_IMDB,SERIES_HERO)
VALUES("THE WALKING DEAD",4.6,8.1,"RICK GRIMES"),
("GAME OF THRONES",4.7,9.2,"EMILIA CLARKE"),
("PRISON BREAK",4.2,8.3,"MICHAEL"),
("MONEY HEIST",4.5,8.2,"PROFESSOR");
DELETE FROM TV_SERIES
WHERE SERIES_RATINGS=4.2;
SELECT*FROM TV_SERIES;
SELECT * FROM TV_SERIES LIMIT 3 OFFSET 3;#SELECTS FROM 4TH INDEX OR GREATER THAN 3


